server:
  port: '9001'
spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/departs?serverTimezone'
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
  logging:
    level:
      org:
        hibernate:
          SQL: debug
spriing:
  jpa:
    show:
      sql: true
